# Generated by Django 3.0.3 on 2020-03-01 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('experiment_name', models.TextField(verbose_name='name of experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('prediction', models.TextField(default='Not available', max_length=100)),
                ('ground_truth', models.TextField(default='No available', max_length=100)),
                ('image', models.TextField(max_length=240)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='human_app.Segment')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('name', models.TextField(default='', verbose_name='feature name')),
                ('value', models.FloatField(default=0.0, verbose_name='feature value')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='human_app.Segment')),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rated', models.BooleanField(default=False)),
                ('winner', models.IntegerField(default=99999999)),
                ('experiment_name', models.TextField(verbose_name='name of experiment')),
                ('segments', models.ManyToManyField(to='human_app.Segment')),
            ],
        ),
    ]
